## 1.3 Yoğunluk Matrislerini Birleştirmek (Combining density matrices)

Yoğunluk matrisleri $\rho_A$ ve $\rho_B$ ile tanımlanan $A$ ve $B$ gibi iki kuantum sistemimiz olduğunda, bunların birleşik durumu olan $\rho_{AB}$ matrisini nasıl yazabiliriz? 

Hafta 0 (Week 0) notlarında, vektörlerle temsil edilen iki saf kuantum durumunun ($|v_1\rangle \in \mathbb{C}^{d_1}$ ve $|v_2\rangle \in \mathbb{C}^{d_2}$), tensör çarpımları ($|v_1\rangle \otimes |v_2\rangle \in \mathbb{C}^{d_1} \otimes \mathbb{C}^{d_2}$) alınarak birleştirilebildiğini görmüştük. Karma durumları (yoğunluk matrislerini) birleştirme kuralının da buna son derece benzer olduğu ve tensör çarpımı kavramının doğrudan bir uzantısı olduğu görülür.

$\rho_A$ ve $\rho_B$ matrislerinin $2 \times 2$ boyutunda olduğu en basit durumla işe başlayalım:

$$\rho_A \otimes \rho_B = \begin{pmatrix} m_{11} & m_{12} \\ m_{21} & m_{22} \end{pmatrix} \otimes \begin{pmatrix} n_{11} & n_{12} \\ n_{21} & n_{22} \end{pmatrix} = \begin{pmatrix} m_{11} \begin{pmatrix} n_{11} & n_{12} \\ n_{21} & n_{22} \end{pmatrix} & m_{12} \begin{pmatrix} n_{11} & n_{12} \\ n_{21} & n_{22} \end{pmatrix} \\ m_{21} \begin{pmatrix} n_{11} & n_{12} \\ n_{21} & n_{22} \end{pmatrix} & m_{22} \begin{pmatrix} n_{11} & n_{12} \\ n_{21} & n_{22} \end{pmatrix} \end{pmatrix} \quad \text{--- (1.34)}$$

Bu blok matris çarpımını açıkça dağıtarak yazarsak, $4 \times 4$ boyutunda şu bileşke matrisi elde ederiz:

$$= \begin{pmatrix} m_{11}n_{11} & m_{11}n_{12} & m_{12}n_{11} & m_{12}n_{12} \\ m_{11}n_{21} & m_{11}n_{22} & m_{12}n_{21} & m_{12}n_{22} \\ m_{21}n_{11} & m_{21}n_{12} & m_{22}n_{11} & m_{22}n_{12} \\ m_{21}n_{21} & m_{21}n_{22} & m_{22}n_{21} & m_{22}n_{22} \end{pmatrix} \quad \text{--- (1.35)}$$

> 📝 **Örnek Soru:** Aşağıdaki iki yoğunluk matrisinin tensör çarpımı yöntemiyle birleşik kuantum durumunu ($\rho_{AB}$) hesaplayınız:
> 
> $$\rho_A = \begin{pmatrix} 0 & 0 \\ 0 & 1 \end{pmatrix} \quad \text{ve} \quad \rho_B = \begin{pmatrix} 1 & 0 \\ 0 & 0 \end{pmatrix}$$
> 
> **Çözüm:**
> Blok matris açılım kuralını (1.34) doğrudan bu matrislere uygulayalım:
> 
> $$\rho_{AB} = \rho_A \otimes \rho_B = \begin{pmatrix} 0 \cdot \rho_B & 0 \cdot \rho_B \\ 0 \cdot \rho_B & 1 \cdot \rho_B \end{pmatrix}$$
> 
> $$\rho_{AB} = \begin{pmatrix} 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 \end{pmatrix} \quad \text{--- (1.36)}$$


In [2]:
import numpy as np

# örnek matrislerimizi tanımlayalım
rho_A = np.array([[0, 0], 
                  [0, 1]])

rho_B = np.array([[1, 0], 
                  [0, 0]])

# Kronecker (Tensör) çarpımı ile birleşik matrisi hesaplayalım
rho_AB = np.kron(rho_A, rho_B)

print("Bilgisayarın hesapladığı 4x4 birleşik yoğunluk matrisi:\n", rho_AB)


Bilgisayarın hesapladığı 4x4 birleşik yoğunluk matrisi:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]


> 🟦 **Tanım 1.3.1 — Tensör Çarpımı.** Herhangi bir $d' \times d$ boyutundaki $\rho_A$ matrisini ve $k' \times k$ boyutundaki $\rho_B$ matrisini ele alalım:
> 
> $$\rho_A = \begin{pmatrix} m_{11} & m_{12} & \dots & m_{1d} \\ m_{21} & m_{22} & \dots & m_{2d} \\ \vdots & \vdots & \ddots & \vdots \\ m_{d'1} & m_{d'2} & \dots & m_{d'd} \end{pmatrix}, \quad \rho_B = \begin{pmatrix} n_{11} & n_{12} & \dots & n_{1k} \\ n_{21} & n_{22} & \dots & n_{2k} \\ \vdots & \vdots & \ddots & \vdots \\ n_{k'1} & n_{k'2} & \dots & n_{k'k} \end{pmatrix} \quad \text{--- (1.37)}$$
> 
> Bu iki matrisin tensör çarpımı, $(d'k') \times (dk)$ boyutunda bir blok matris oluşturur ve şu şekilde verilir:
> 
> $$\rho_{AB} = \rho_A \otimes \rho_B = \begin{pmatrix} m_{11}\rho_B & m_{12}\rho_B & \dots & m_{1d}\rho_B \\ m_{21}\rho_B & m_{22}\rho_B & \dots & m_{2d}\rho_B \\ \vdots & \vdots & \ddots & \vdots \\ m_{d'1}\rho_B & m_{d'2} & \dots & m_{d'd}\rho_B \end{pmatrix} \quad \text{--- (1.38)}$$

⚠️ **Önemli Uyarı:** Tıpkı standart matris çarpımında olduğu gibi, tensör çarpımı işlemi de **değişmeli değildir (non-commutative)**. Yani genel olarak $\rho_A \otimes \rho_B \neq \rho_B \otimes \rho_A$ durumu geçerlidir.


> 📝 **Örnek 1.3.1** Aşağıdaki biri $3 \times 3$, diğeri $2 \times 2$ boyutunda olan iki yoğunluk matrisini ele alalım :
> 
> $$\rho_A = \frac{1}{4} \begin{pmatrix} 1 & 1 & 0 \\ 1 & 3 & 1 \\ 0 & 1 & 1 \end{pmatrix} \quad \text{ve} \quad \rho_B = \frac{1}{2} \begin{pmatrix} 1 & -i \\ i & 1 \end{pmatrix}$$
> 
> 1. İlk olarak **$\rho_A \otimes \rho_B$** işlemini blok matris kuralına göre hesaplayalım:
> 
> $$\rho_A \otimes \rho_B = \frac{1}{8} \begin{pmatrix} 1\rho_B & 1\rho_B & 0\rho_B \\ 1\rho_B & 3\rho_B & 1\rho_B \\ 0\rho_B & 1\rho_B & 1\rho_B \end{pmatrix} = \frac{1}{8} \begin{pmatrix} 1 & -i & 1 & -i & 0 & 0 \\ i & 1 & i & 1 & 0 & 0 \\ 1 & -i & 3 & -3i & 1 & -i \\ i & 1 & 3i & 3 & i & 1 \\ 0 & 0 & 1 & -i & 1 & -i \\ 0 & 0 & i & 1 & i & 1 \end{pmatrix} \quad \text{--- (1.39)}$$


> 2. Şimdi ise matrislerin sırasını değiştirerek **$\rho_B \otimes \rho_A$** işlemini hesaplayalım:
> 
> $$\rho_B \otimes \rho_A = \frac{1}{8} \begin{pmatrix} 1\rho_A & -i\rho_A \\ i\rho_A & 1\rho_A \end{pmatrix}$$
> 
> $$\rho_B \otimes \rho_A = \frac{1}{8} \begin{pmatrix} 1 & 1 & 0 & -i & -i & 0 \\ 1 & 3 & 1 & -i & -3i & -i \\ 0 & 1 & 1 & 0 & -i & -i \\ i & i & 0 & 1 & 1 & 0 \\ i & 3i & i & 1 & 3 & 1 \\ 0 & i & i & 0 & 1 & 1 \end{pmatrix} \quad \text{--- (1.40)}$$
> 
> Elde ettiğimiz (1.39) ve (1.40) numaralı büyük matrisler incelendiğinde, elemanların yerlerinin tamamen farklı olduğu açıkça görülür. Böylece **$\rho_A \otimes \rho_B \neq \rho_B \otimes \rho_A$** olduğu bilgisayar hassasiyetinde de ispatlanmış olur.
