

## 2.1 Dolanıklık (Entanglement)

Her biri saf (pure) bir durumda olan iki bağımsız kuantum sistemini ($A$ ve $B$) bir araya getirdiğimizde, bu iki kübitin ortak birleşik durumu tensör çarpımı ile verilir:

$$|\Psi\rangle_{AB} = |\psi_1\rangle_A \otimes |\psi_2\rangle_B \quad \text{--- (2.1)}$$

Doğrudan bu formda yazılabilen veya bu formdaki saf çarpım durumlarının istatistiksel bir karışımı (convex combination) şeklinde ifade edilebilen tüm iki-kübitlik durumlara kuantum literatüründe **ayrılabilir durumlar (separable states)** denir. 

**Dolanık durumlar (entangled states)** ise en temel tanımıyla *ayrılabilir olmayan* durumlardır. Başka bir deyişle, saf bir $|\psi\rangle$ birleşik kuantum durumu, eğer olası hiçbir $|\psi_1\rangle$ ve $|\psi_2\rangle$ tekil vektör seçimi için çarpım şeklinde **yazılamıyorsa** dolanıktır:

$$|\psi\rangle \neq |\psi_1\rangle \otimes |\psi_2\rangle \quad \text{--- (2.2)}$$

Benzer şekilde, bir $\rho$ karma durumu (mixed state), eğer Denklem (2.1)'deki gibi saf çarpım durumlarının bir olasılık kombinasyonu şeklinde yazılamıyorsa dolanık bir karma durum olarak adlandırılır.


> 📝 **Örnek 2.1.1 — İki Kübitlik Dolanık Durum Örneği.** Dolanık kuantum durumlarının en popüler örneği, meşhur EPR çiftidir:
> 
> $$|\text{EPR}\rangle_{AB} = \frac{1}{\sqrt{2}}\Big( |00\rangle_{AB} + |11\rangle_{AB} \Big) \quad \text{--- (2.3)}$$

> 
> dolanıklık miktarını nicelendirdiğimizde daha net göreceğimiz üzere bu durum, kesin ve matematiksel bir anlamda iki kübit için tanımlanabilecek **"en yoğun/maksimum dolanık" (maximally entangled)** durumdur. EPR çiftinden tamamen farklı matris yapılarına sahip olan ancak onunla kuruşu kuruşuna aynı dolanıklık "miktarına" sahip başka iki-kübitlik durumlar da mevcuttur; bu diğer maksimum dolanık durumları ilerde gösterelim.


EPR çifti son derece özel ve simetrik bir matematiksel yapıya sahiptir; öyle ki bu durum pek çok farklı tabanda tamamen aynı katsayılarla yeniden yazılabilir. Örneğin, bu durumu **Hadamard tabanında** ifade edersek terimler yine kusursuz bir simetriyle şu şekilde açılır:

$$\frac{1}{\sqrt{2}}\Big( |++\rangle_{AB} + |--\rangle_{AB} \Big) \quad \text{--- (2.4)}$$

Bu muazzam simetri şu anlama gelir: Eğer iki kübitle de aynı anda ister standart hesapsal tabanda, ister Hadamard tabanında bir ölçüm yaparsanız, iki tarafın elde edeceği ölçüm sonuçları her zaman **birebir aynı (korele)** çıkacaktır (Alice '0' ölçerse Bob da '0' ölçer; Alice '+' ölçerse Bob da '+' ölçer). Birkaç hafta içinde, bu benzersiz özelliğin aslında sadece ve sadece EPR çiftine özgü olduğunu matematiksel olarak göstereceğiz; yani bu özelliği sağlayan yegane iki-kübitlik kuantum durumu EPR çiftinin ta kendisidir!


> 🟦 **Alıştırma 2.1.1 ** $\rho_{AB}$ matrisinin iki kübitlik ayrılabilir (separable) bir kuantum durumu olduğunu varsayalım. Eğer bu $\rho_{AB}$ durumu üzerinde yapılan iki-kübitlik standart taban ölçümü **her zaman aynı sonucu** (yani yalnızca $|00\rangle$ veya $|11\rangle$) üretiyorsa; aynı durum üzerinde Hadamard tabanında yapılacak bir ölçümün **farklı sonuçlar verme olasılığının kesinlikle sıfırdan büyük ($>0$) olmak zorunda olduğunu** ispatlayınız. Bu ispattan yararlanarak, EPR çiftinin (2.3) ayrılabilir bir durum olamayacağını (yani dolanık olduğunu) çelişki yoluyla kanıtlayınız.

**İspat:**
Alıştırmadaki iddiayı adım adım çelişki (olmayana ergi) yöntemiyle ispatlayalım.

**Adım 1:** $\rho_{AB}$ ayrılabilir bir durum olduğundan, bazı saf çarpım durumlarının karışımı olarak yazılabilir: $\rho_{AB} = \sum_i p_i |\phi_i\rangle\langle\phi_i|_A \otimes |\psi_i\rangle\langle\psi_i|_B$. 
Standart tabanda ölçüm yapıldığında zıt sonuçların ($|01\rangle$ ve $|10\rangle$) gelme olasılığının tam olarak sıfır ($0$) olduğu bize verilmiştir. Bir kuantum durumunda olasılığın sıfır çıkması, o durumun içindeki hiçbir çarpım bileşeninin bu zıt durumları barındırmaması gerektiği anlamına gelir. Dolayısıyla, her bir $i$ bileşeni için ya her iki taraf da kesinlikle $|0\rangle$ durumundadır ya da kesinlikle $|1\rangle$ durumundadır. Yani ayrılabilir durumumuz en genel haliyle şu forma zorlanır:
$$\rho_{AB} = p_0 |00\rangle\langle00| + p_1 |11\rangle\langle11|$$

**Adım 2:** Şimdi bu durumu **Hadamard tabanında** ölçtüğümüzde zıt bir sonuç (örneğin $|+-\rangle$) elde etme olasılığını Born kuralı yardımıyla hesaplayalım. Taban elemanlarının izdüşümlerini hatırlayalım: $|\langle +|0\rangle|^2 = 1/2$ ve $|\langle -|1\rangle|^2 = 1/2$.
$$p(+-) = \langle +- | \rho_{AB} | +- \rangle = p_0 |\langle +|0\rangle|^2 |\langle -|0\rangle|^2 + p_1 |\langle +|1\rangle|^2 |\langle -|1\rangle|^2$$
$$p(+-) = p_0 \left(\frac{1}{2} \cdot \frac{1}{2}\right) + p_1 \left(\frac{1}{2} \cdot \frac{1}{2}\right) = \frac{1}{4}(p_0 + p_1)$$

Yoğunluk matrisinin izi 1 olmak zorunda olduğundan $p_0 + p_1 = 1$'dir. Değeri yerine koyarsak:
$$p(+-) = \frac{1}{4} > 0$$

Görüldüğü üzere, standart tabanda her zaman aynı sonucu veren herhangi bir ayrılabilir durum, Hadamard tabanına geçildiğinde **en az $1/4$ olasılıkla mutlaka farklı/zıt sonuçlar üretmek zorundadır**.

**Adım 3 (EPR Çiftinin Dolanıklık Kanıtı):**
Şimdi EPR çiftini ele alalım. Denklem (2.4)'te gösterdiğimiz üzere EPR çifti Hadamard tabanında ölçüldüğünde her zaman aynı sonucu verir ($|++\rangle$ veya $|--\rangle$); yani zıt bir sonuç ($|+-\rangle$ veya $|-+\rangle$) verme olasılığı **tam olarak sıfırdır ($0$)**. 

Eğer EPR çifti ayrılabilir bir durum olsaydı, yukarıda yaptığımız ispata göre Hadamard tabanında zıt sonuç verme olasılığının sıfırdan büyük ($1/4$) çıkması gerekirdi. Bu durum açık bir matematiksel çelişki doğurur. Dolayısıyla, EPR çifti **kesinlikle ayrılabilir bir durum olamaz; doğası gereği dolanıktır (entangled)**. 


In [ ]:
import numpy as np

# Temel qubit durumları 
q0 = np.array([1, 0])
q1 = np.array([0, 1])


# Adım 1'deki standart tabanda sadece aynı sonuçları veren ayrılabilir karma durum (Örn: p0=0.5, p1=0.5)
# rho = 0.5*|00><00| + 0.5*|11><11|
zero_zero = np.kron(q0, q0)
one_one = np.kron(q1, q1)
rho_ayrilabilir = 0.5 * np.outer(zero_zero, zero_zero) + 0.5 * np.outer(one_one, one_one)

# Hadamard taban elemanları
plus = (q0 + q1) / np.sqrt(2)
minus = (q0 - q1) / np.sqrt(2)

# Zıt bir sonuç olan |+-> durum vektörü ve izdüşüm matrisi
plus_minus_ket = np.kron(plus, minus)

# Born Kuralı ile ayrılabilir durumun |+-> gelme olasılığını hesaplayalım: tr(M * rho)
p_plus_minus = np.dot(plus_minus_ket, np.dot(rho_ayrilabilir, plus_minus_ket))

print(f"Standart tabanda korele olan ayrılabilir durumun Hadamard tabanında |+-> verme olasılığı: {p_plus_minus:.2f}")
print(f"Teoride ispatladığımız 1/4 (0.25) değerine eşit mi?: {np.isclose(p_plus_minus, 0.25)}")


Standart tabanda korele olan ayrılabilir durumun Hadamard tabanında |+-> verme olasılığı: 0.25
Teoride ispatladığımız 1/4 (0.25) değerine eşit mi?: True


Bir diğer sıra dışı ve ilginç özelliği ise **"monogami" (monogamy / tek eşlilik)** ilkesidir. Monogami ilkesine göre, eğer iki kuantum sistemi ($A$ ve $B$) kendi aralarında **maksimum dolanık** (maximally entangled) durumdaysa, bu iki sistem evrendeki (veya çevredeki) başka hiçbir üçüncü bir kuantum sistemiyle en ufak bir dolanıklık bağı kuramaz! 

Fiziksel olarak bunun anlamı şudur: Maksimum dolanık bir çift, evrenin geri kalanıyla zorunlu olarak bir tensör çarpımı ($\otimes$) ilişkisi içinde, yani tamamen bağımsız olmak zorundadır. Bu ilke, kuantum şifrelemenin (QKD) mutlak güvenliğinin ana kalkanıdır; çünkü Alice ve Bob aralarında tam bir EPR çifti paylaştıklarında, bir casusun (Eve) bu sisteme gizlice dolanıklık yoluyla sızması fiziksel olarak imkansız hale gelir.


> 📝 **Örnek 2.1.2** Aşağıdaki iki kübitlik kuantum durumunu ele alalım:
> 
> $$|\Psi\rangle_{AB} = \frac{1}{\sqrt{2}}\Big( |01\rangle_{AB} + |11\rangle_{AB} \Big) \quad \text{--- (2.5)}$$
> 
> Örnek 2.1.1'deki EPR çiftinin aksine, bu durum **dolanık değildir**. Çünkü terimleri ortak çarpan parantezine aldığımızda sistem iki bağımsız tekil kübitin çarpımı şeklinde kolayca ayrışabilir:
> 
> $$|\Psi\rangle_{AB} = \frac{1}{\sqrt{2}}\big( |0\rangle_A + |1\rangle_A \big) \otimes |1\rangle_B = |+\rangle_A \otimes |1\rangle_B$$


> 🟦 **Tanım 2.1.1 — Dolanıklık ve Ayrılabilirlik (Formal).** $A$ ve $B$ adında iki kuantum sistemini ele alalım. Eğer birleşik $\rho_{AB}$ yoğunluk matrisi, bazı $\{p_i\}$ olasılık dağılımları ile $A$ ve $B$ sistemlerine ait $\{\rho_i^A\}$ ve $\{\rho_i^B\}$ yoğunluk matrisi kümeleri cinsinden şu şekilde bir karışım olarak yazılabiliyorsa **ayrılabilir (separable)** bir durumdur:
> 
> $$\rho_{AB} = \sum_{i} p_i \rho_i^A \otimes \rho_i^B \quad \text{--- (2.6)}$$
> 
> Eğer matris için böyle bir matematiksel ayrışım **asla yazılamıyorsa**, $\rho_{AB}$ durumu **dolanık (entangled)** olarak adlandırılır.
> 
> Özel olarak, eğer birleşik durum saf bir durum ise ($\rho_{AB} = |\Psi\rangle\langle\Psi|_{AB}$), bu $|\Psi\rangle_{AB}$ durumunun ayrılabilir olabilmesi için gerek ve yeter şart, yalnızca sistemi iki bağımsız ket vektörünün doğrudan çarpımı şeklinde yazabilmektir:
> 
> $$|\Psi\rangle_{AB} = |\psi\rangle_A \otimes |\psi\rangle_B \quad \text{--- (2.7)}$$


> 📝 **Örnek 2.1.3 ** Aşağıdaki iki kübitlik birleşik yoğunluk matrisini ele alalım :
> 
> $$\rho_{AB} = \frac{1}{3}|1\rangle\langle1|_A \otimes |0\rangle\langle0|_B + \frac{2}{3}|-\rangle\langle-|_A \otimes |+\rangle\langle+|_B \quad \text{--- (2.8)}$$
> 
> Bu matris yapısı gereği doğrudan Denklem (2.6)'daki genel tanıma uymaktadır. Dolayısıyla bu durum **dolanık değildir; ayrılabilir (separable) bir karma durumdur**. 
> 
> **Çok Önemli Not:** Bir durumun ayrılabilir olması, $A$ and $B$ sistemlerinin birbirinden tamamen bağımsız (ilişkisiz) olduğu anlamına gelmez! Görüldüğü üzere iki tarafın durumları olasılık katsayıları üzerinden birbirine bağlıdır. Ancak bu bağ, kuantum dünyasına özgü gizemli bir dolanıklık değil, tamamen klasik olasılık kurallarıyla açıklanabilen **klasik bir korelasyondur (classical correlation)**.


In [2]:
import numpy as np

# Temel qubit durumları
q0 = np.array([1, 0])
q1 = np.array([0, 1])
plus = (q0 + q1) / np.sqrt(2)
minus = (q0 - q1) / np.sqrt(2)

# 1. Terim: |1><1| tensor |0><0|
term1 = np.kron(np.outer(q1, q1), np.outer(q0, q0))

# 2. Terim: |-><-| tensor |+><+|
term2 = np.kron(np.outer(minus, minus), np.outer(plus, plus))

# Özgün katsayılarla birleştirme (1/3 ve 2/3)
rho_klasik_korelasyon = (1/3) * term1 + (2/3) * term2

print("İnşa edilen 4x4 klasik korelasyon matrisi:\n", np.round(rho_klasik_korelasyon, 3))
print(f"\nMatris izi (tr): {np.trace(rho_klasik_korelasyon):.1f} (1.0 olmalı)")


İnşa edilen 4x4 klasik korelasyon matrisi:
 [[ 0.167  0.167 -0.167 -0.167]
 [ 0.167  0.167 -0.167 -0.167]
 [-0.167 -0.167  0.5    0.167]
 [-0.167 -0.167  0.167  0.167]]

Matris izi (tr): 1.0 (1.0 olmalı)


> 📝 **Örnek 2.1.4** Önceki bölümlerde Tanım 1.4.2 ile verdiğimiz, genel formu $\rho_{XQ} = \sum_i p_i |x\rangle\langle x|_X \otimes \rho_i^Q$ şeklinde olan tüm **klasik-kuantum durumları (cq-states)**, yapıları gereği Tanım 2.1.1'deki ayrışım kuralına doğrudan uyarlar. Dolayısıyla, tüm cq-durumları doğası gereği **ayrılabilir (separable)** durumlardır; içlerinde kuantum dolanıklığı barındırmazlar.

Kuantum dolanıklığı ile klasik korelasyonlar arasındaki o muazzam ve derin ayrımı görmek adına şimdi şu iki farklı iki-kübitlik durumu çok dikkatli bir şekilde karşılaştıralım:

$$\rho_{AB} = \frac{1}{2}|0\rangle\langle0|_A \otimes |0\rangle\langle0|_B + \frac{1}{2}|1\rangle\langle1|_A \otimes |1\rangle\langle1|_B \quad \text{ve} \quad \sigma_{AB} = |\text{EPR}\rangle\langle\text{EPR}|_{AB} \quad \text{--- (2.9)}$$

İlk durum olan $\rho_{AB}$, tamamen klasik bir yazı-tura mekanizmasıyla oluşturulmuş **klasik korelasyonlu karma bir durumdur**. İkinci durum olan $\sigma_{AB}$ ise bildiğimiz meşhur saf **EPR dolanık durumudur**. 

Eğer Alice kendi kübitini ($A$) standart hesapsal tabanda ölçerse; $\rho_{AB}$ durumunda Alice '0' gördüğünde Bob kesinlikle $|0\rangle_B$ durumunda kalır, Alice '1' gördüğünde Bob kesinlikle $|1\rangle_B$ durumunda kalır. Bu durumun kuruşu kuruşuna aynısı EPR dolanık durumu ($\sigma_{AB}$) için de tamamen geçerlidir! Yani, sadece standart tabana bakarak bu iki durumun farkını asla anlayamayız.




Farkı görmek için Alice'in kübitini standart taban yerine **Hadamard tabanında** ($\{|+\rangle, |-\rangle\}$) ölçtüğünü varsayalım. Alice'in uzayındaki ölçüm operatörlerimiz $M_+ = |+\rangle\langle+|_A \otimes \mathbb{I}_B$ ve $M_- = |-\rangle\langle-|_A \otimes \mathbb{I}_B$ olacaktır. 

Klasik korelasyonlu $\rho_{AB}$ durumu üzerinde bu deneyi gerçekleştirdiğimizde ve Alice'in ölçüm sonucunda "$+$" elde ettiğini bildiğimizde, **ölçüm sonrası birleşik kuantum durumu** Born kuralı gereği şu matematiksel basamakları takip eder:

$$\rho_{|+\rangle_A}^{AB} = \frac{(|+\rangle\langle+|_A \otimes \mathbb{I}_B) \, \rho_{AB} \, (|+\rangle\langle+|_A \otimes \mathbb{I}_B)}{\text{tr}\big((|+\rangle\langle+|_A \otimes \mathbb{I}_B)\rho_{AB}\big)} \quad \text{--- (2.10)}$$

Daha önce bulduğumuz $|\langle +|0\rangle|^2 = 1/2$ ve $|\langle +|1\rangle|^2 = 1/2$ iç çarpım değerlerini denklemde yerine koyup payda sadeleştirmesini yapalım:

$$= 2 \cdot \left( \frac{1}{2} \cdot \frac{1}{2} |+\rangle\langle+|_A \otimes |0\rangle\langle0|_B + \frac{1}{2} \cdot \frac{1}{2} |+\rangle\langle+|_A \otimes |1\rangle\langle1|_B \right) \quad \text{--- (2.11)}$$

$$= |+\rangle\langle+|_A \otimes \frac{\mathbb{I}_B}{2} \quad \text{--- (2.12)}$$


Denklem (2.12)'den açıkça görülüyor, klasik korelasyonlu durum ölçüldüğünde Bob'un elinde kalan indirgenmiş marjinal durum **$\rho_{|+\rangle_A}^B = \mathbb{I}_B/2$** olur; yani tamamen belirsiz bir **maksimum karma durumdur**. Alice'in ne ölçtüğü, Bob'un lokal durumunun belirsizliğini zerre kadar azaltamamıştır.

Buna tamamen zıt bir senaryo olarak, şimdi de aynı deneyi EPR dolanık durumu ($\sigma_{AB}$) üzerinde uygulayalım.

$$|\text{EPR}\rangle_{AB} = \frac{1}{\sqrt{2}}\Big( |00\rangle_{AB} + |11\rangle_{AB} \Big) = \frac{1}{\sqrt{2}}\Big( |++\rangle_{AB} + |--\rangle_{AB} \Big) \quad \text{--- (2.13)}$$

Eğer $\sigma_{AB}$ durumu üzerinde Alice ölçüm yapıp "$+$" sonucunu elde ederse, Bob'un tarafında kalan indirgenmiş kuantum durumu doğrudan **$\sigma_{|+\rangle_A}^B = |+\rangle\langle+|_B$** olur. 

Felsefi ve fiziksel açıdan bu muazzam bir farktır! Bob'un elinde kalan durum tamamen **saf (pure) bir durumdur**, yani belirsizlik sıfırdır. Bu durum, kuantum dolanıklığı olan $\sigma_{AB}$ durumunun içindeki korelasyon bağlarının, klasik yazı-tura yöntemleriyle üretilen $\rho_{AB}$ durumundaki bağlardan **katbekat daha güçlü ve derin olduğunun** en kesin matematiksel kanıtıdır. Kuantum şifreleme protokolleri güçlerini tamamen bu dolanıklık korelasyonundan alırlar.
